/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Veena Iyer
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise enterprise;
    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;
        popOrganizationComboBox();
        //employeejComboBox.removeAllItems();
        popData();
    }

    public void popOrganizationComboBox() {
        organizationjComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationjComboBox.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        employeejComboBox.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            employeejComboBox.addItem(employee);
        }
    }
    
    private void populateRoleComboBox(Organization organization){
        rolejComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            rolejComboBox.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) userjTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) userjTable.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userjTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        orgTypeTxt1 = new javax.swing.JLabel();
        orgTypeTxt2 = new javax.swing.JLabel();
        orgTypeTxt3 = new javax.swing.JLabel();
        orgTypeTxt4 = new javax.swing.JLabel();
        orgTypeTxt5 = new javax.swing.JLabel();
        usernameTxtFld = new javax.swing.JTextField();
        organizationjComboBox = new javax.swing.JComboBox();
        employeejComboBox = new javax.swing.JComboBox();
        rolejComboBox = new javax.swing.JComboBox();
        addEmpBtn = new javax.swing.JButton();
        passwordTxtFld = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        userjTable.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        userjTable.setForeground(new java.awt.Color(51, 204, 255));
        userjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userjTable);
        if (userjTable.getColumnModel().getColumnCount() > 0) {
            userjTable.getColumnModel().getColumn(0).setResizable(false);
            userjTable.getColumnModel().getColumn(1).setResizable(false);
        }

        backbtn.setBackground(new java.awt.Color(51, 102, 255));
        backbtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        orgTypeTxt1.setBackground(new java.awt.Color(51, 102, 255));
        orgTypeTxt1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        orgTypeTxt1.setForeground(new java.awt.Color(51, 102, 255));
        orgTypeTxt1.setText("Organization");

        orgTypeTxt2.setBackground(new java.awt.Color(51, 102, 255));
        orgTypeTxt2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        orgTypeTxt2.setForeground(new java.awt.Color(51, 102, 255));
        orgTypeTxt2.setText("Employee");

        orgTypeTxt3.setBackground(new java.awt.Color(51, 102, 255));
        orgTypeTxt3.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        orgTypeTxt3.setForeground(new java.awt.Color(51, 102, 255));
        orgTypeTxt3.setText("Role");

        orgTypeTxt4.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        orgTypeTxt4.setForeground(new java.awt.Color(51, 102, 255));
        orgTypeTxt4.setText("Username");

        orgTypeTxt5.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        orgTypeTxt5.setForeground(new java.awt.Color(51, 102, 255));
        orgTypeTxt5.setText("Password");

        usernameTxtFld.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N

        organizationjComboBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        organizationjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationjComboBoxActionPerformed(evt);
            }
        });

        employeejComboBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N

        rolejComboBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N

        addEmpBtn.setBackground(new java.awt.Color(51, 102, 255));
        addEmpBtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        addEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        addEmpBtn.setText("Add >>");
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        passwordTxtFld.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(orgTypeTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(rolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(orgTypeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(employeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(orgTypeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(organizationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(orgTypeTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orgTypeTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgTypeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgTypeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgTypeTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgTypeTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgTypeTxt5)
                    .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEmpBtn)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        String userName = usernameTxtFld.getText();
        String password = passwordTxtFld.getText();
        Organization organization = (Organization) organizationjComboBox.getSelectedItem();
        Employee employee = (Employee) employeejComboBox.getSelectedItem();
        Role role = (Role) rolejComboBox.getSelectedItem();
        
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        
        popData();
        JOptionPane.showMessageDialog(this, "Added Successfully");
        usernameTxtFld.setText("");
        passwordTxtFld.setText("");
    }//GEN-LAST:event_addEmpBtnActionPerformed

    private void organizationjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationjComboBoxActionPerformed
        Organization organization = (Organization) organizationjComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_organizationjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox employeejComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgTypeTxt1;
    private javax.swing.JLabel orgTypeTxt2;
    private javax.swing.JLabel orgTypeTxt3;
    private javax.swing.JLabel orgTypeTxt4;
    private javax.swing.JLabel orgTypeTxt5;
    private javax.swing.JComboBox organizationjComboBox;
    private javax.swing.JPasswordField passwordTxtFld;
    private javax.swing.JComboBox rolejComboBox;
    private javax.swing.JTable userjTable;
    private javax.swing.JTextField usernameTxtFld;
    // End of variables declaration//GEN-END:variables
}
