/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PotentialDonor;

import userinterface.Receptionist.*;
import Business.EcoSystem;
import Business.Enterprise.CampEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.DonorAccount;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiranhun
 */
public class NewPotenialDonorRemoteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewPotenialDonorCredentialJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private ReceptionistOrganization receptionistOrganization;
    private CampEnterprise enterprise;
    private DonorAccount donor;
    //private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public NewPotenialDonorRemoteJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        //system = dB4OUtil.retrieveSystem();
        this.system = system;
        this.setSize(1680, 1050);
        this.userProcessContainer = userProcessContainer;
        btnSchedule.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fRadioButton = new javax.swing.JRadioButton();
        mRadioButton = new javax.swing.JRadioButton();
        txtWeight = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        checkboxpanel = new javax.swing.JPanel();
        diabeticjCheckBox = new javax.swing.JCheckBox();
        HyperTensionjCheckBox = new javax.swing.JCheckBox();
        smokingjCheckBox = new javax.swing.JCheckBox();
        drinkingjCheckBox = new javax.swing.JCheckBox();
        asthamajCheckBox = new javax.swing.JCheckBox();
        epilepsyCheckBox = new javax.swing.JCheckBox();
        strokejCheckBox = new javax.swing.JCheckBox();
        heartDieseaseJcheckbox = new javax.swing.JCheckBox();
        stdjCheckBox = new javax.swing.JCheckBox();
        hepatitisjCheckBox = new javax.swing.JCheckBox();
        hivjCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radioBtnLiver = new javax.swing.JRadioButton();
        radioBtnKidney = new javax.swing.JRadioButton();
        radioBtnEyes = new javax.swing.JRadioButton();
        radioBtnHeart = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrgan = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(51, 102, 255));
        btnSave.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Create");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(51, 102, 255));
        backbtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("*****************************Sign Up To Save Lives***********************************");

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Name*");

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Last");

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("First");

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Gender*");

        fRadioButton.setBackground(new java.awt.Color(51, 102, 255));
        fRadioButton.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        fRadioButton.setText("F");
        fRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fRadioButtonActionPerformed(evt);
            }
        });

        mRadioButton.setBackground(new java.awt.Color(51, 102, 255));
        mRadioButton.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        mRadioButton.setText("M");
        mRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRadioButtonActionPerformed(evt);
            }
        });

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Weight*");

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Age*");

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Blood Type");

        checkboxpanel.setBackground(new java.awt.Color(204, 204, 204));

        diabeticjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        diabeticjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        diabeticjCheckBox.setText("Diabetic");

        HyperTensionjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        HyperTensionjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        HyperTensionjCheckBox.setText("HyperTension");

        smokingjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        smokingjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        smokingjCheckBox.setText("Smoking");

        drinkingjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        drinkingjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        drinkingjCheckBox.setText("Drinking");

        asthamajCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        asthamajCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        asthamajCheckBox.setText("Asthama");
        asthamajCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asthamajCheckBoxActionPerformed(evt);
            }
        });

        epilepsyCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        epilepsyCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        epilepsyCheckBox.setText("Epilepsy");

        strokejCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        strokejCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        strokejCheckBox.setText("Stroke");

        heartDieseaseJcheckbox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        heartDieseaseJcheckbox.setForeground(new java.awt.Color(51, 102, 255));
        heartDieseaseJcheckbox.setText("Heart Diesease");

        stdjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        stdjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        stdjCheckBox.setText("STD");

        hepatitisjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        hepatitisjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        hepatitisjCheckBox.setText("Hepatitis");

        hivjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        hivjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        hivjCheckBox.setText("HIV");

        javax.swing.GroupLayout checkboxpanelLayout = new javax.swing.GroupLayout(checkboxpanel);
        checkboxpanel.setLayout(checkboxpanelLayout);
        checkboxpanelLayout.setHorizontalGroup(
            checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkboxpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diabeticjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(strokejCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heartDieseaseJcheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HyperTensionjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(smokingjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(stdjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addComponent(hepatitisjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hivjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addComponent(drinkingjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asthamajCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(epilepsyCheckBox)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        checkboxpanelLayout.setVerticalGroup(
            checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkboxpanelLayout.createSequentialGroup()
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diabeticjCheckBox)
                            .addComponent(HyperTensionjCheckBox)
                            .addComponent(smokingjCheckBox)
                            .addComponent(drinkingjCheckBox)
                            .addComponent(asthamajCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strokejCheckBox)
                            .addComponent(heartDieseaseJcheckbox)
                            .addComponent(stdjCheckBox)
                            .addComponent(hepatitisjCheckBox)
                            .addComponent(hivjCheckBox)))
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(epilepsyCheckBox)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Welcome!! ");

        jLabel10.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Select the Organs you wish to donate");

        radioBtnLiver.setText("Liver");

        radioBtnKidney.setText("Kidney");

        radioBtnEyes.setText("Eyes");

        radioBtnHeart.setText("Heart");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Receptionist/right.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblOrgan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selected Organs"
            }
        ));
        jScrollPane2.setViewportView(tblOrgan);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Receptionist/left.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSchedule.setBackground(new java.awt.Color(51, 102, 255));
        btnSchedule.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        btnSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedule.setText("Schedule");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnLiver, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioBtnHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioBtnEyes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(radioBtnKidney, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(409, 409, 409))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addComponent(checkboxpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fRadioButton)
                                    .addComponent(mRadioButton)
                                    .addComponent(radioBtnLiver))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnKidney))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioBtnEyes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioBtnHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(checkboxpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSchedule)
                    .addComponent(btnSave))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here
        if(validateForm()){
            for(Network network : system.getNetworkList()){
                for(Enterprise enterprise1 : network.getEnterpriseDirectory().getEnterpriseList()){
                    if(enterprise1.getEnterpriseType().getValue().equals("Camp Enterprise")){
                        CampEnterprise enterprise = (CampEnterprise)enterprise1;
                        DonorAccount potentialDonor = enterprise.getPotentialDonorAccountDirectory().addPotentialDonor();
                        potentialDonor.setFirstName(txtFirstName.getText());
                        potentialDonor.setLastName(txtLastName.getText());
                        potentialDonor.setAge(Integer.parseInt(txtAge.getText()));
                        potentialDonor.setWeight(Double.parseDouble(txtWeight.getText()));
                        potentialDonor.setBloodType(txtBloodType.getText());
                        potentialDonor.setScheduled(false);
                        potentialDonor.setRemoteDonor(true);
                        for(int i =0; i<tblOrgan.getRowCount() ; i++){
                            String s = (String)tblOrgan.getValueAt(i, 0);
                            potentialDonor.getOrganList().addOrgan(s);
                        }
                        String gender;
                        if(fRadioButton.isSelected())
                        gender="F";
                        else if(mRadioButton.isSelected())
                        gender = "M";
                        for (Component component : checkboxpanel.getComponents()) {
                            if(component.getClass().equals(JCheckBox.class)){
                                JCheckBox checkBox = (JCheckBox)component;
                                if(diabeticjCheckBox.isSelected())
                                potentialDonor.setDiabetic(true);
                                if(HyperTensionjCheckBox.isSelected())
                                potentialDonor.setHypertension(true);
                                if(smokingjCheckBox.isSelected())
                                potentialDonor.setDoesSmoke(true);
                                if(drinkingjCheckBox.isSelected())
                                potentialDonor.setDoesDrink(true);
                                if(asthamajCheckBox.isSelected())
                                potentialDonor.setHasAsthama(true);
                                if(epilepsyCheckBox.isSelected())
                                potentialDonor.setEpilepsy(true);
                                if(strokejCheckBox.isSelected())
                                potentialDonor.setStroke(true);
                                if(heartDieseaseJcheckbox.isSelected())
                                potentialDonor.setStroke(true);
                                if(hepatitisjCheckBox.isSelected())
                                potentialDonor.setHepatitis(true);
                                if(stdjCheckBox.isSelected())
                                    potentialDonor.setStd(true);
                            }
                        }
                        JOptionPane.showMessageDialog(null,"Potential Donor details added");
                        donor = potentialDonor;
                        btnSave.setEnabled(false);
                        btnSchedule.setEnabled(true);
                        
                    }
//                    dB4OUtil.storeSystem(system);
                }
            }
            //dB4OUtil.storeSystem(system);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean validateForm(){
        if(!txtFirstName.getText().isEmpty() && !txtLastName.getText().isEmpty()){
            if(!txtWeight.getText().isEmpty()){
               if(!txtBloodType.getText().isEmpty()){
                   if(fRadioButton.isSelected() || mRadioButton.isSelected())
                    return true;
               } 
            }
        }
        return false;
    }
        
    
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void asthamajCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asthamajCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asthamajCheckBoxActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblOrgan.getModel();
        if(radioBtnLiver.isSelected()){
            model.addRow(new Object[]{"Liver"});
            radioBtnLiver.setSelected(false);
            radioBtnLiver.setEnabled(false);
        }
        if(radioBtnKidney.isSelected()){
            model.addRow(new Object[]{"Kidney"});
            radioBtnKidney.setSelected(false);
            radioBtnKidney.setEnabled(false);
        }
        if(radioBtnEyes.isSelected()){
            model.addRow(new Object[]{"Eyes"});
            radioBtnEyes.setSelected(false);
            radioBtnEyes.setEnabled(false);
        }
        if(radioBtnHeart.isSelected()){
            model.addRow(new Object[]{"Heart"});
            radioBtnHeart.setSelected(false);
            radioBtnHeart.setEnabled(false);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblOrgan.getModel();
        int row = tblOrgan.getSelectedRow();
        if(row>=0){
            Object obj = tblOrgan.getValueAt(row, 0);
            if(obj.toString().equals("Liver")){
                radioBtnLiver.setSelected(false);
                radioBtnLiver.setEnabled(true);
            }
            if(obj.toString().equals("Kidney")){
                radioBtnKidney.setSelected(false);
                radioBtnKidney.setEnabled(true);
            }
            if(obj.toString().equals("Eyes")){
                radioBtnEyes.setSelected(false);
                radioBtnEyes.setEnabled(true);
            }
            if(obj.toString().equals("Heart")){
                radioBtnHeart.setSelected(false);
                radioBtnHeart.setEnabled(true);
            }
            model.removeRow(row);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        // TODO add your handling code here:
        for(Network network : system.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof CampEnterprise){
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    userProcessContainer.add("SchedulerJPanel", new SchedulerJPanel(userProcessContainer, userAccount,  receptionistOrganization,  enterprise,  system, String.valueOf(donor.getId())));
                    layout.next(userProcessContainer);
                }
            }
        }
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void fRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fRadioButtonActionPerformed
        // TODO add your handling code here:
        mRadioButton.setSelected(false);
    }//GEN-LAST:event_fRadioButtonActionPerformed

    private void mRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRadioButtonActionPerformed
        // TODO add your handling code here:
        fRadioButton.setSelected(false);
    }//GEN-LAST:event_mRadioButtonActionPerformed

    public void refreshScreen(){
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtBloodType.setText("");
        txtWeight.setText("");
        fRadioButton.setSelected(false);
        mRadioButton.setSelected(false);
        radioBtnEyes.setSelected(false);
        radioBtnHeart.setSelected(false);
        radioBtnKidney.setSelected(false);
        radioBtnLiver.setSelected(false);
        diabeticjCheckBox.setSelected(false);
        HyperTensionjCheckBox.setSelected(false);
        smokingjCheckBox.setSelected(false);
        drinkingjCheckBox.setSelected(false);
        asthamajCheckBox.setSelected(false);
        epilepsyCheckBox.setSelected(false);
        heartDieseaseJcheckbox.setSelected(false);
        strokejCheckBox.setSelected(false);
        stdjCheckBox.setSelected(false);
        hepatitisjCheckBox.setSelected(false);
        hivjCheckBox.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HyperTensionjCheckBox;
    private javax.swing.JCheckBox asthamajCheckBox;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JPanel checkboxpanel;
    private javax.swing.JCheckBox diabeticjCheckBox;
    private javax.swing.JCheckBox drinkingjCheckBox;
    private javax.swing.JCheckBox epilepsyCheckBox;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JCheckBox heartDieseaseJcheckbox;
    private javax.swing.JCheckBox hepatitisjCheckBox;
    private javax.swing.JCheckBox hivjCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JRadioButton radioBtnEyes;
    private javax.swing.JRadioButton radioBtnHeart;
    private javax.swing.JRadioButton radioBtnKidney;
    private javax.swing.JRadioButton radioBtnLiver;
    private javax.swing.JCheckBox smokingjCheckBox;
    private javax.swing.JCheckBox stdjCheckBox;
    private javax.swing.JCheckBox strokejCheckBox;
    private javax.swing.JTable tblOrgan;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
