/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userinterface.Analytics.AnalyticsJPanel;

/**
 *
 * @author Veena Iyer
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        ArrayList<Network> networkList=ecosystem.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k=0;k<organizationList.size();k++){
                    organization=organizationList.get(i);
                    organizationNode=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        rightJpanel = new javax.swing.JPanel();
        mngNetworkBtn = new javax.swing.JButton();
        mngEnterpriseBtn = new javax.swing.JButton();
        mngEnterpriseAdminBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectedValue = new javax.swing.JLabel();
        Analytics = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        leftJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTree.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        jTree.setForeground(new java.awt.Color(0, 51, 204));
        jTree.setAlignmentX(2.0F);
        jTree.setAlignmentY(2.0F);
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(leftJPanel);

        rightJpanel.setBackground(new java.awt.Color(255, 255, 255));

        mngNetworkBtn.setBackground(new java.awt.Color(51, 102, 255));
        mngNetworkBtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        mngNetworkBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngNetworkBtn.setText("Manage Network");
        mngNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngNetworkBtnActionPerformed(evt);
            }
        });

        mngEnterpriseBtn.setBackground(new java.awt.Color(51, 102, 255));
        mngEnterpriseBtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        mngEnterpriseBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnterpriseBtn.setText("Manage Enterprise");
        mngEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnterpriseBtnActionPerformed(evt);
            }
        });

        mngEnterpriseAdminBtn.setBackground(new java.awt.Color(51, 102, 255));
        mngEnterpriseAdminBtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        mngEnterpriseAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnterpriseAdminBtn.setText("Manage Enterprise Admin");
        mngEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Selected Business >>");

        selectedValue.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        selectedValue.setForeground(new java.awt.Color(51, 102, 255));
        selectedValue.setText("View Selected");

        Analytics.setBackground(new java.awt.Color(51, 102, 255));
        Analytics.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        Analytics.setForeground(new java.awt.Color(255, 255, 255));
        Analytics.setText("Analytics");
        Analytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpanelLayout = new javax.swing.GroupLayout(rightJpanel);
        rightJpanel.setLayout(rightJpanelLayout);
        rightJpanelLayout.setHorizontalGroup(
            rightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(rightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngEnterpriseBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mngNetworkBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mngEnterpriseAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(Analytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightJpanelLayout.setVerticalGroup(
            rightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(rightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(mngNetworkBtn)
                .addGap(27, 27, 27)
                .addComponent(mngEnterpriseBtn)
                .addGap(28, 28, 28)
                .addComponent(mngEnterpriseAdminBtn)
                .addGap(27, 27, 27)
                .addComponent(Analytics)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(rightJpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngNetworkBtnActionPerformed
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngNetworkBtnActionPerformed

    private void mngEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnterpriseBtnActionPerformed
        ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnterpriseBtnActionPerformed

    private void mngEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnterpriseAdminBtnActionPerformed
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnterpriseAdminBtnActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
            selectedValue.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged

    private void AnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("AnaluticsJpanel", new AnalyticsJPanel(ecosystem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analytics;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton mngEnterpriseAdminBtn;
    private javax.swing.JButton mngEnterpriseBtn;
    private javax.swing.JButton mngNetworkBtn;
    private javax.swing.JPanel rightJpanel;
    private javax.swing.JLabel selectedValue;
    // End of variables declaration//GEN-END:variables
}
