/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.campDoctor;

import Business.Assignment.Assignment;
import Business.Enterprise.CampEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organ.Organ;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.DonorAccount;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author kiranhun
 */

public class OrgansListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form organsListJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private CampEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    
    public OrgansListJPanel(JPanel userProcessContainer, UserAccount userAccount, CampEnterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = (CampEnterprise)enterprise;
        this.userAccount = userAccount;
        this.network=network;
        populateAvailabilityTable();
        populateDonatedOrganTable();
    }

    public void populateAvailabilityTable(){
        DefaultTableModel model = (DefaultTableModel) tblAvailableOrgans.getModel();
        model.setRowCount(0);
        for(DonorAccount donor : enterprise.getPotentialDonorAccountDirectory().getPotentialDonorList()){
            if(donor.isDeceased()){
                for(Organ organ : donor.getOrganList().getOrganList()){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = donor;
                    row[1] = organ.getOrganID();
                    row[2] = organ.getOrganName();
                    model.addRow(row);
                }
            }
        }
    }
    
    public void populateDonatedOrganTable(){
        DefaultTableModel model = (DefaultTableModel) tblDonatedOrgans.getModel();
        model.setRowCount(0);
        for(Assignment assignment : network.getAssignmentDirectory().getAssignmentList()){
            Object[] row = new Object[model.getColumnCount()];
            row[0] = assignment.getDonor().getId();
            row[1] = assignment.getOrgan().getOrganID();
            row[2] = assignment.getOrgan().getOrganName();
            row[3] = assignment.getPatient().getPatientID();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableOrgans = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonatedOrgans = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblAvailableOrgans.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        tblAvailableOrgans.setForeground(new java.awt.Color(51, 102, 255));
        tblAvailableOrgans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DonorID", "OrganID", "Organ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAvailableOrgans);
        if (tblAvailableOrgans.getColumnModel().getColumnCount() > 0) {
            tblAvailableOrgans.getColumnModel().getColumn(0).setResizable(false);
            tblAvailableOrgans.getColumnModel().getColumn(1).setResizable(false);
            tblAvailableOrgans.getColumnModel().getColumn(2).setResizable(false);
        }

        tblDonatedOrgans.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        tblDonatedOrgans.setForeground(new java.awt.Color(51, 102, 255));
        tblDonatedOrgans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DonorID", "OrganID", "Organ", "PatientID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDonatedOrgans);
        if (tblDonatedOrgans.getColumnModel().getColumnCount() > 0) {
            tblDonatedOrgans.getColumnModel().getColumn(0).setResizable(false);
            tblDonatedOrgans.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Organs Available");

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Organs Donated");

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Tracking Screen");

        backbtn.setBackground(new java.awt.Color(51, 102, 255));
        backbtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAvailableOrgans;
    private javax.swing.JTable tblDonatedOrgans;
    // End of variables declaration//GEN-END:variables
}
