/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Receptionist;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.CampEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.DonorAccount;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiranhun
 */
public class NewPotenialDonorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewPotenialDonorCredentialJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private ReceptionistOrganization receptionistOrganization;
    private CampEnterprise enterprise;
    
    
    public NewPotenialDonorDetailsJPanel(JPanel userProcessContainer, UserAccount account, ReceptionistOrganization receptionistOrganization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.receptionistOrganization = receptionistOrganization;
        this.enterprise = (CampEnterprise)enterprise;
//        populate();
//        pouplateDoc();
    }
    
//    private void pouplateDoc(){
//        comboBoxDDocList.removeAllItems();
//        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//              if(organization.getName().equals("Doctor Organization")){
//                  for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
//                        comboBoxDDocList.addItem(employee);        }
//              }
//        }
//    }
    
//    private void populate(){
//        DefaultTableModel dtm = (DefaultTableModel)tblDonor.getModel();
//        dtm.setRowCount(0);
//        for(DonorAccount donor : enterprise.getPotentialDonorAccountDirectory().getPotentialDonorList()){
//            Object[] row = new Object[dtm.getColumnCount()];
//            row[0]=donor;
//            row[1]=donor.getFirstName();
//            row[2]=donor.getLastName();
//            dtm.addRow(row);
//        }
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fRadioButton = new javax.swing.JRadioButton();
        mRadioButton = new javax.swing.JRadioButton();
        txtWeight = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        checkboxpanel = new javax.swing.JPanel();
        diabeticjCheckBox = new javax.swing.JCheckBox();
        HyperTensionjCheckBox = new javax.swing.JCheckBox();
        smokingjCheckBox = new javax.swing.JCheckBox();
        drinkingjCheckBox = new javax.swing.JCheckBox();
        asthamajCheckBox = new javax.swing.JCheckBox();
        epilepsyCheckBox = new javax.swing.JCheckBox();
        strokejCheckBox = new javax.swing.JCheckBox();
        heartDieseaseJcheckbox = new javax.swing.JCheckBox();
        stdjCheckBox = new javax.swing.JCheckBox();
        hepatitisjCheckBox = new javax.swing.JCheckBox();
        hivjCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radioBtnLiver = new javax.swing.JRadioButton();
        radioBtnKidney = new javax.swing.JRadioButton();
        radioBtnEyes = new javax.swing.JRadioButton();
        radioBtnHeart = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrgan = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(51, 102, 255));
        btnSave.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Create");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(51, 102, 255));
        backbtn.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("*****************************Sign Up To Save Lives***********************************");

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Name*");

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Last");

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("First");

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Gender*");

        fRadioButton.setBackground(new java.awt.Color(51, 102, 255));
        fRadioButton.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        fRadioButton.setText("F");
        fRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fRadioButtonActionPerformed(evt);
            }
        });

        mRadioButton.setBackground(new java.awt.Color(51, 102, 255));
        mRadioButton.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        mRadioButton.setText("M");
        mRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRadioButtonActionPerformed(evt);
            }
        });

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Weight*");

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Age*");

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Blood Type");

        checkboxpanel.setBackground(new java.awt.Color(204, 204, 204));

        diabeticjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        diabeticjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        diabeticjCheckBox.setText("Diabetic");

        HyperTensionjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        HyperTensionjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        HyperTensionjCheckBox.setText("HyperTension");

        smokingjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        smokingjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        smokingjCheckBox.setText("Smoking");

        drinkingjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        drinkingjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        drinkingjCheckBox.setText("Drinking");

        asthamajCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        asthamajCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        asthamajCheckBox.setText("Asthama");
        asthamajCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asthamajCheckBoxActionPerformed(evt);
            }
        });

        epilepsyCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        epilepsyCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        epilepsyCheckBox.setText("Epilepsy");

        strokejCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        strokejCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        strokejCheckBox.setText("Stroke");

        heartDieseaseJcheckbox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        heartDieseaseJcheckbox.setForeground(new java.awt.Color(51, 102, 255));
        heartDieseaseJcheckbox.setText("Heart Diesease");

        stdjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        stdjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        stdjCheckBox.setText("STD");

        hepatitisjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        hepatitisjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        hepatitisjCheckBox.setText("Hepatitis");

        hivjCheckBox.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        hivjCheckBox.setForeground(new java.awt.Color(51, 102, 255));
        hivjCheckBox.setText("HIV");

        javax.swing.GroupLayout checkboxpanelLayout = new javax.swing.GroupLayout(checkboxpanel);
        checkboxpanel.setLayout(checkboxpanelLayout);
        checkboxpanelLayout.setHorizontalGroup(
            checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkboxpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diabeticjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(strokejCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HyperTensionjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heartDieseaseJcheckbox))
                .addGap(28, 28, 28)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smokingjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinkingjCheckBox)
                    .addComponent(hepatitisjCheckBox))
                .addGap(27, 27, 27)
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asthamajCheckBox)
                    .addComponent(hivjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(epilepsyCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkboxpanelLayout.setVerticalGroup(
            checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkboxpanelLayout.createSequentialGroup()
                .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diabeticjCheckBox)
                            .addComponent(HyperTensionjCheckBox)
                            .addComponent(smokingjCheckBox)
                            .addComponent(drinkingjCheckBox)
                            .addComponent(asthamajCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkboxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strokejCheckBox)
                            .addComponent(heartDieseaseJcheckbox)
                            .addComponent(stdjCheckBox)
                            .addComponent(hepatitisjCheckBox)
                            .addComponent(hivjCheckBox)))
                    .addGroup(checkboxpanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(epilepsyCheckBox)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Add Potential Donor Screen");

        jLabel10.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Select the Organs you wish to donate");

        radioBtnLiver.setText("Liver");

        radioBtnKidney.setText("Kidney");

        radioBtnEyes.setText("Eyes");

        radioBtnHeart.setText("Heart");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Receptionist/right.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblOrgan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selected Organs"
            }
        ));
        jScrollPane2.setViewportView(tblOrgan);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Receptionist/left.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioBtnLiver, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioBtnKidney, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(radioBtnEyes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioBtnHeart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fRadioButton)
                            .addComponent(mRadioButton)
                            .addComponent(radioBtnLiver)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnKidney)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnEyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnHeart))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)))
                .addGap(26, 26, 26)
                .addComponent(checkboxpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here
        if(validateForm()){
            
            DonorAccount potentialDonor = enterprise.getPotentialDonorAccountDirectory().addPotentialDonor();
            potentialDonor.setFirstName(txtFirstName.getText());
            potentialDonor.setLastName(txtLastName.getText());
            potentialDonor.setAge(Integer.parseInt(txtAge.getText()));
            potentialDonor.setWeight(Double.parseDouble(txtWeight.getText()));
            potentialDonor.setBloodType(txtBloodType.getText());
            potentialDonor.setScheduled(false);
            for(int i =0; i<tblOrgan.getRowCount() ; i++){
                String s = (String)tblOrgan.getValueAt(i, 0);
                potentialDonor.getOrganList().addOrgan(s);
            }
            String gender;
            if(fRadioButton.isSelected())
                gender="F";
            else if(mRadioButton.isSelected())
                gender = "M";
            for (Component component : checkboxpanel.getComponents()) {
                if(component.getClass().equals(JCheckBox.class)){
                    JCheckBox checkBox = (JCheckBox)component;
                    if(diabeticjCheckBox.isSelected())
                        potentialDonor.setDiabetic(true);
                    if(HyperTensionjCheckBox.isSelected())
                        potentialDonor.setHypertension(true);
                    if(smokingjCheckBox.isSelected())
                        potentialDonor.setDoesSmoke(true);
                    if(drinkingjCheckBox.isSelected())
                        potentialDonor.setDoesDrink(true);
                    if(asthamajCheckBox.isSelected())
                        potentialDonor.setHasAsthama(true);
                    if(epilepsyCheckBox.isSelected())
                        potentialDonor.setEpilepsy(true);
                    if(strokejCheckBox.isSelected())
                        potentialDonor.setStroke(true);
                    if(heartDieseaseJcheckbox.isSelected())
                        potentialDonor.setStroke(true);
                    if(hepatitisjCheckBox.isSelected())
                        potentialDonor.setHepatitis(true);
                    if(stdjCheckBox.isSelected())
                        potentialDonor.setStd(true);
                }
            }
            
            JOptionPane.showMessageDialog(null,"Potential Donor details added");
            //populate();
            refreshScreen();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean validateForm(){
        if(!txtFirstName.getText().isEmpty() && !txtLastName.getText().isEmpty()){
            if(!txtWeight.getText().isEmpty()){
               if(!txtBloodType.getText().isEmpty()){
                   if(fRadioButton.isSelected() || mRadioButton.isSelected())
                    return true;
               } 
            }
        }
        return false;
    }
        
    
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void asthamajCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asthamajCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asthamajCheckBoxActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblOrgan.getModel();
        if(radioBtnLiver.isSelected()){
            model.addRow(new Object[]{"Liver"});
            radioBtnLiver.setSelected(false);
            radioBtnLiver.setEnabled(false);
        }
        if(radioBtnKidney.isSelected()){
            model.addRow(new Object[]{"Kidney"});
            radioBtnKidney.setSelected(false);
            radioBtnKidney.setEnabled(false);
        }
        if(radioBtnEyes.isSelected()){
            model.addRow(new Object[]{"Eyes"});
            radioBtnEyes.setSelected(false);
            radioBtnEyes.setEnabled(false);
        }
        if(radioBtnHeart.isSelected()){
            model.addRow(new Object[]{"Heart"});
            radioBtnHeart.setSelected(false);
            radioBtnHeart.setEnabled(false);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblOrgan.getModel();
        int row = tblOrgan.getSelectedRow();
        if(row>=0){
            Object obj = tblOrgan.getValueAt(row, 0);
            if(obj.toString().equals("Liver")){
                radioBtnLiver.setSelected(false);
                radioBtnLiver.setEnabled(true);
            }
            if(obj.toString().equals("Kidney")){
                radioBtnKidney.setSelected(false);
                radioBtnKidney.setEnabled(true);
            }
            if(obj.toString().equals("Eyes")){
                radioBtnEyes.setSelected(false);
                radioBtnEyes.setEnabled(true);
            }
            if(obj.toString().equals("Heart")){
                radioBtnHeart.setSelected(false);
                radioBtnHeart.setEnabled(true);
            }
            model.removeRow(row);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void fRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fRadioButtonActionPerformed
        // TODO add your handling code here:
        mRadioButton.setSelected(false);
    }//GEN-LAST:event_fRadioButtonActionPerformed

    private void mRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRadioButtonActionPerformed
        // TODO add your handling code here:
        fRadioButton.setSelected(false);
    }//GEN-LAST:event_mRadioButtonActionPerformed

    public void refreshScreen(){
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtBloodType.setText("");
        txtWeight.setText("");
        fRadioButton.setSelected(false);
        mRadioButton.setSelected(false);
        radioBtnEyes.setSelected(false);
        radioBtnHeart.setSelected(false);
        radioBtnKidney.setSelected(false);
        radioBtnLiver.setSelected(false);
        diabeticjCheckBox.setSelected(false);
        HyperTensionjCheckBox.setSelected(false);
        smokingjCheckBox.setSelected(false);
        drinkingjCheckBox.setSelected(false);
        asthamajCheckBox.setSelected(false);
        epilepsyCheckBox.setSelected(false);
        heartDieseaseJcheckbox.setSelected(false);
        strokejCheckBox.setSelected(false);
        stdjCheckBox.setSelected(false);
        hepatitisjCheckBox.setSelected(false);
        hivjCheckBox.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HyperTensionjCheckBox;
    private javax.swing.JCheckBox asthamajCheckBox;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel checkboxpanel;
    private javax.swing.JCheckBox diabeticjCheckBox;
    private javax.swing.JCheckBox drinkingjCheckBox;
    private javax.swing.JCheckBox epilepsyCheckBox;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JCheckBox heartDieseaseJcheckbox;
    private javax.swing.JCheckBox hepatitisjCheckBox;
    private javax.swing.JCheckBox hivjCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JRadioButton radioBtnEyes;
    private javax.swing.JRadioButton radioBtnHeart;
    private javax.swing.JRadioButton radioBtnKidney;
    private javax.swing.JRadioButton radioBtnLiver;
    private javax.swing.JCheckBox smokingjCheckBox;
    private javax.swing.JCheckBox stdjCheckBox;
    private javax.swing.JCheckBox strokejCheckBox;
    private javax.swing.JTable tblOrgan;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
